### PR TITLE
Nz/4183 FFP Bug

### LINKED ISSUE #4183: [Bug] Issue when entering numbers into Estimated Quarterly Expenditure table
Some numbers (I tried 29 and 888 as examples) change the input values (# shown in the field, not necessarily what is saved in the database).

See the video below

### This task is done when...

- [x] bug investigated further to determine root cause
- [x] bug resolved

---

https://images.zenhubusercontent.com/113234315/63a2ef2c-8b03-42d1-b807-87b09e3868fb/numberbug.mov

### PR DESCRIPTION
**Pull request by Sun-Mountain**
Resolves #4183

### Description
Some numbers (specifically 28, 29, 56, 57) change the input values (# shown in the field, not necessarily what is saved in the database).

### Significant changes or possible side effects
Changed where the value was being set (in the controller) and then in the component, use `.toFixed(0)` to keep it whole numbers.

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| The FFP table in Budget and FFP in activites | User types in any number (specifically 28, 29, 56, and 57) | The number stays whole. | jest |

### Steps to manually verify this change

1. Go to Budget and FFP page
2. Type in percentage cells 28, 29, 56, and 57
3. Confirm numbers are consistent and correct based on user input.

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [x] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [x] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [x] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [x] Design has approved the experience
- [x] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Nice work

File: web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js [hunk 1]
```diff
@@ -80,21 +80,17 @@ const CostAllocateFFPQuarterly = ({
...
   }, [quarterlyFFP[year].subtotal.contractors]); // eslint-disable-line react-hooks/exhaustive-deps
 
-  const setInHouse =
-    quarter =>
-    ({ target: { value } }) => {
-      setValue(`[${quarter}].inHouse.percent`, value / 100);
-      setInHouseFFP(activityIndex, year, quarter, value);
-      announce(activityId, year, quarter, 'inHouse');
-    };
+  const setInHouse = quarter => value => {
```
Comment (thetif) [inline web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js:83]: you could just combine these args and functions here and have
```
const setInHouse = (quarter, value) => {
...
```
then when you use it down below you could just call
```
setInHouse(q, value)
```
it was curried before so that you could use it like
```
onChange={setInHouse(q)}
```
and then the onChange would be called on the function above and you don't have to destructure the value. I can explain that better if that made no sense

File: web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js [hunk 2]
```diff
@@ -80,21 +80,17 @@ const CostAllocateFFPQuarterly = ({
...
+  };
 
-  const setContractor =
-    quarter =>
-    ({ target: { value } }) => {
-      setValue(`[${quarter}].contractors.percent`, value / 100);
-      setContractorFFP(activityIndex, year, quarter, value);
-      announce(activityId, year, quarter, 'contractors');
-    };
+  const setContractor = quarter => value => {
```
Comment (thetif) [inline web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js:89]: same as above

File: web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js [hunk 3]
```diff
@@ -148,17 +144,20 @@ const CostAllocateFFPQuarterly = ({
                   <Controller
                     control={control}
                     name={`[${q}].inHouse.percent`}
-                    render={({ field: { onBlur, ...props } }) => (
+                    value={quarterlyFFP[year][q].inHouse.percent}
```
Comment (thetif) [inline web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js:147]: you don't really need to do this, it's probably better to change it back to how it was before

File: web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js [hunk 4]
```diff
@@ -148,17 +144,20 @@ const CostAllocateFFPQuarterly = ({
...
                         label={`federal share for ffy ${year}, quarter ${q}, state`}
                         labelClassName="sr-only"
-                        onChange={setInHouse(q)}
+                        onChange={({ target: { value } }) => {
+                          setInHouse(q)(value);
+                        }}
                         onBlur={onBlur}
                         round
-                        value={quarterlyFFP[year][q].inHouse.percent * 100}
+                        value={(value * 100).toFixed(0)}
```
Comment (thetif) [inline web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js:160]: if you remove the value from controller and render, then this would be like it was before but with toFixed(0)
```
value={(quarterlyFFP[year][q].inHouse.percent * 100).toFixed(0)}
```

File: web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js [hunk 5]
```diff
@@ -210,17 +209,20 @@ const CostAllocateFFPQuarterly = ({
                   <Controller
                     control={control}
                     name={`[${q}].contractors.percent`}
-                    render={({ field: { onBlur, ...props } }) => (
+                    value={quarterlyFFP[year][q].contractors.percent * 100}
```
Comment (thetif) [inline web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js:212]: same as above

File: web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js [hunk 6]
```diff
@@ -388,6 +388,116 @@ describe('the cost allocation quarterly FFP component', () => {
...
+                  }
+                }
+              }
+            }
+          }
+        }
+      }
+    );
+
+    expect(
```
Comment (thetif) [inline web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js:488]: for these tests you should try setting the value to 29 and 28 because that's where the problem was happening

File: web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js [hunk 7]
```diff
@@ -422,13 +532,31 @@ describe('the cost allocation quarterly FFP component', () => {
...
+        name: 'federal share for ffy 2022, quarter 1, state'
+      })
+    ).toHaveValue('57');
+
+    await user.clear(
+      screen.getByRole('textbox', {
+        name: 'federal share for ffy 2022, quarter 1, state'
+      })
+    );
+    await user.type(
```
Comment (thetif) [inline web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js:549]: you should do this with those values above and just have them blank to start or like 25 or something, whatever it looked like when it was throwing the error

**Review by thetif — APPROVED** [review]
looks good! I'm glad you were able to figure out where it was happening. Minor changes just for code clarity

File: web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js (hunk 6 above)
Comment (Sun-Mountain) [reply web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js:488]: I did on lines 415 and 419 :)

File: web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js (hunk 7 above)
Comment (Sun-Mountain) [reply web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js:549]: on 492 and 498 :)

**Review by tbolt — APPROVED** [review]

**Review by mirano-darren — APPROVED** [review]
Looks good to me! Tested number 1-100 and the bug didn't appear once.

Note: Preview builds aren't letting me log in, so I tested this locally

**Review by jeromeleecms — COMMENTED** [review]
The numbers in the table seems to be behaving oddly: 

image

Its also behaving strangely when I put numbers in, sometimes the numbers don't "stay" - I put it 44 and it changed it to 4...

**Comment by mirano-darren** [comment]
> The numbers in the table seems to be behaving oddly:
> 
> image
> 
> Its also behaving strangely when I put numbers in, sometimes the numbers don't "stay" - I put it 44 and it changed it to 4...

Can confirm. certain numbers have the same issue as before. Here's a list of the ones I found:
7, 14, 28, 29, 55, 56, 57, 58,

**Review by jeromeleecms — APPROVED** [review]
This appears to be resolved. Thank you @Sun-Mountain! This is GTG on my end.
